-- MySQL Script generated by MySQL Workbench
-- Sat Nov  9 17:23:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `cpf` VARCHAR(11) NULL,
  `data_nascimento` DATE NULL,
  `telefone` VARCHAR(15) NULL,
  `tipo_usuario` ENUM('FUNCIONARIO','CLIENTE') NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `codigo_funcionario` VARCHAR(20) NULL,
  `cargo` VARCHAR(50) NULL,
  `usuario_id` INT NULL,
  PRIMARY KEY (`id_funcionario`),
  CONSTRAINT `fk_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `id_usuario_fk`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(10) NULL,
  `local` VARCHAR(100) NULL,
  `numero_casa` INT NULL,
  `bairro` VARCHAR(50) NULL,
  `cidade` VARCHAR(50) NULL,
  `estado` VARCHAR(2) NULL,
  `usuario_id` INT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `id_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `usuario_fk_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conta` (
  `id_conta` INT NOT NULL AUTO_INCREMENT,
  `numero_conta` VARCHAR(20) NULL,
  `agencia` VARCHAR(10) NULL,
  `saldo` DECIMAL(15,2) NULL,
  `tipo_conta` ENUM('POUPANCA','CORRENTE') NULL,
  `cliente_id` INT NULL,
  PRIMARY KEY (`id_conta`),
  INDEX `fk_cliente_id_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta_corrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conta_corrente` (
  `id_conta_corrente` INT NOT NULL AUTO_INCREMENT,
  `limite` DECIMAL(15,2) NULL,
  `data_vencimento` DATE NULL,
  `conta_id` INT NULL,
  PRIMARY KEY (`id_conta_corrente`),
  INDEX `fk_conta_id_idx` (`conta_id` ASC),
  CONSTRAINT `fk_conta_id`
    FOREIGN KEY (`conta_id`)
    REFERENCES `mydb`.`conta` (`id_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta_poupanca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conta_poupanca` (
  `id_conta_poupanca` INT NOT NULL AUTO_INCREMENT,
  `taxa_rendimento` DECIMAL(5,2) NULL,
  `conta_id` INT NULL,
  PRIMARY KEY (`id_conta_poupanca`),
  INDEX `fk_conta_id_idx` (`conta_id` ASC),
  CONSTRAINT `id_conta_fk`
    FOREIGN KEY (`conta_id`)
    REFERENCES `mydb`.`conta` (`id_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transacao` (
  `id_transacao` INT NOT NULL AUTO_INCREMENT,
  `tipo_transacao` ENUM('DEPOSITO', 'SAQUE', 'TRANSFERENCIA') NULL,
  `valor` DECIMAL(15,2) NULL,
  `data_hora` TIMESTAMP NULL,
  `conta_id` INT NULL,
  PRIMARY KEY (`id_transacao`),
  INDEX `fk_conta_id_idx` (`conta_id` ASC),
  CONSTRAINT `conta_fk_id`
    FOREIGN KEY (`conta_id`)
    REFERENCES `mydb`.`conta` (`id_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relatorio` (
  `id_relatorio` INT NOT NULL AUTO_INCREMENT,
  `tipo_relatorio` VARCHAR(50) NULL,
  `data_geracao` TIMESTAMP NULL,
  `conteudo` TEXT NULL,
  `funcionario_id` INT NULL,
  PRIMARY KEY (`id_relatorio`),
  INDEX `fk_funcionario_id_idx` (`funcionario_id` ASC),
  CONSTRAINT `fk_funcionario_id`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `mydb`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;CREATE TABLE IF NOT EXISTS `mydb`.`conta_poupanca` (   `id_conta_poupanca` INT NOT NULL AUTO_INCREMENT,   `taxa_rendimento` DECIMAL(5,2) NULL,   `conta_id` INT NULL,   PRIMARY KEY (`id_conta_poupanca`),   INDEX `fk_conta_id_idx` (`conta_id` ASC),   CONSTRAINT `fk_conta_id`     FOREIGN KEY (`conta_id`)     REFERENCES `mydb`.`conta` (`id_conta`)     ON DELETE NO ACTION     ON UPDATE NO ACTION) ENGINE = InnoDB
